server {
    listen 80;
    
    # Root directory for static files
    root /usr/share/nginx/html;
    
    index index.html index.htm;

    # React Router config: try to serve file, if not found, fallback to index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Cache static assets
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public";
    }
}
